#!/usr/bin/perl -w

# Parse the output generated by pfopt-real.py.
#  Usage: pfopt-parse-output.pl <output file>

my %stonks = ();

open( my $fh, '<', "$ARGV[0]" ) or die $!;
while ( <$fh> )  {
	if ( $_ !~ /^\d/ )  {
		next;
	}

	chomp( $_ );
	$_ =~ s/\d+[\s\t]+//;
	my ( $company_name, $ticker, $num_stonks ) = split( /\s{2,}/, $_ );

	$stonks{$ticker} = $num_stonks;
}
close( $fh );

my $st = '';
my @top5_stonks = ();
foreach $st ( sort {$stonks{$a} <=> $stonks{$b}} keys %stonks ) {

	# $st is the ticker, $stonks{$st} is the number
	# print "$st, $stonks{$st}\n";
	push ( @top5_stonks, "$st" );
}

if ( scalar @top5_stonks < 5 )  {
	foreach (@top5_stonks)  {
		print "$_\n";
	}
}
else  {
	print "$top5_stonks[-1]\n";
	print "$top5_stonks[-2]\n";
	print "$top5_stonks[-3]\n";
	print "$top5_stonks[-4]\n";
	print "$top5_stonks[-5]\n";
}


